"""API tests for the Notifications endpoints — empty state, preferences, ownership on read/delete.

Notifications are generated by domain events (see the integration test for the incident-driven
flow); here we drive the read/manage endpoints and the preference defaults directly.
"""

from __future__ import annotations

import uuid

from httpx import AsyncClient
from sqlalchemy.ext.asyncio import AsyncSession

from tests.factories import auth_user, bearer


async def test_empty_inbox_and_unread_count(client: AsyncClient, db: AsyncSession) -> None:
    token, _ = await auth_user(client, db, "u@ex.com", "citizen")
    listing = await client.get("/api/v1/notifications", headers=bearer(token))
    assert listing.status_code == 200 and listing.json()["pagination"]["total"] == 0
    count = await client.get("/api/v1/notifications/unread-count", headers=bearer(token))
    assert count.json()["count"] == 0


async def test_preferences_default_then_update(client: AsyncClient, db: AsyncSession) -> None:
    token, _ = await auth_user(client, db, "p@ex.com", "citizen")
    default = await client.get("/api/v1/notifications/preferences", headers=bearer(token))
    assert default.json() == {"email": True, "sms": True, "in_app": True}

    updated = await client.patch(
        "/api/v1/notifications/preferences", json={"sms": False}, headers=bearer(token)
    )
    assert updated.json() == {"email": True, "sms": False, "in_app": True}
    # persisted
    again = await client.get("/api/v1/notifications/preferences", headers=bearer(token))
    assert again.json()["sms"] is False


async def test_mark_read_requires_ownership(client: AsyncClient, db: AsyncSession) -> None:
    token, _ = await auth_user(client, db, "o@ex.com", "citizen")
    missing = await client.post(
        f"/api/v1/notifications/{uuid.uuid4()}/read", headers=bearer(token)
    )
    assert missing.status_code == 404


async def test_delete_missing_is_404(client: AsyncClient, db: AsyncSession) -> None:
    token, _ = await auth_user(client, db, "d@ex.com", "citizen")
    resp = await client.delete(f"/api/v1/notifications/{uuid.uuid4()}", headers=bearer(token))
    assert resp.status_code == 404
