.DEFAULT_GOAL := help
.PHONY: help dev ios android web build lint typecheck clean
help:      ; @echo "dev | ios | android | web | build"
dev:       ; @bun run dev
ios:       ; @bun run ios
android:   ; @bun run android
web:       ; @bun run web
build:     ; @bun run build
lint:      ; @bun run lint
typecheck: ; @bun run typecheck
clean:     ; @rm -rf .expo node_modules dist
